name: Build and deploy Node.js app to Azure Web App - octa-poc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Step 1: Build client
      - name: Install client dependencies and build React app
        run: |
          cd my-app
          npm install
          npm run build

      # Step 2: Install server deps
      - name: Install server dependencies
        run: |
          cd server
          npm install

      # Step 3: Copy client build to server folder
      - name: Copy client build to server
        run: |
          rm -rf server/client_build
          cp -r my-app/dist server/client_build

      # Step 4: Upload the built server for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06A78EB98D6A417A869B10E10B94F2BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B5F040660864629B5E59B9D58539232 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE7E1C6EEA894368A4E46F25B9BAA533 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'octa-poc'
          slot-name: 'Production'
          package: .
